# Generated by Django 5.1 on 2024-09-11 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="manufactured",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="update_at",
            field=models.DateField(auto_now=True, verbose_name="updated"),
        ),
    ]
