# Generated by Django 5.1 on 2024-10-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("editing_is_active", "Can edit is_active"),
                    ("editing_description", "Can edit description"),
                    ("editing_category", "Can edit category"),
                ],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="active"),
        ),
    ]
